
// Provides interface for writing moderately big letters

const char letters[26][6][6] = {
                            {   "AAAAA",
                                "A   A",
                                "AAAAA",
                                "A   A",
                                "A   A"},

                            {   "BBBB ",
                                "B   B",
                                "BBBB",
                                "B   B",
                                "BBBB"},

                            {   "CCCCC",
                                "C",
                                "C",
                                "C",
                                "CCCCC"},

                            {   "DDDD ",
                                "D   D",
                                "D   D",
                                "D   D",
                                "DDDD"},

                            {   "EEEEE",
                                "E",
                                "EEE",
                                "E",
                                "EEEEE"},

                            {   "FFFFF",
                                "F",
                                "FFF",
                                "F",
                                "F"},

                            {   "GGGGG",
                                "G",
                                "G  GG",
                                "G   G",
                                "GGGGG"},

                            {   "H   H",
                                "H   H",
                                "HHHHH",
                                "H   H",
                                "H   H"},

                            {   "IIIII",
                                "  I",
                                "  I",
                                "  I",
                                "IIIII"},

                            {   " JJJJ",
                                "    J",
                                "    J",
                                "   JJ",
                                "JJJ"},

                            {   "K   K",
                                "K  K",
                                "KKK",
                                "K  K",
                                "K   K"},

                            {   "L",
                                "L",
                                "L",
                                "L",
                                "LLLLL"},

                            {   "M   M",
                                "MM MM",
                                "M M M",
                                "M   M",
                                "M   M"},

                            {   "N   N",
                                "NN  N",
                                "N N N",
                                "N  NN",
                                "N   N"},

                            {   "OOOOO",
                                "O   O",
                                "O   O",
                                "O   O",
                                "OOOOO"},

                            {   "PPPPP",
                                "P   P",
                                "PPPP",
                                "P",
                                "P"},

                            {   "QQQQQ",
                                "Q   Q",
                                "Q   Q",
                                "Q  QQ",
                                "QQQQQ"},

                            {   "RRRRR",
                                "R   R",
                                "RRRRR",
                                "R  R",
                                "R   R"},

                            {   " SSSS",
                                "S",
                                " SSS",
                                "    S",
                                "SSSS"},

                            {   "TTTTT",
                                "  T",
                                "  T",
                                "  T",
                                "  T"},

                            {   "U   U",
                                "U   U",
                                "U   U",
                                "U   U",
                                "UUUUU"},

                            {   "V   V",
                                "V   V",
                                "V   V",
                                " V V",
                                "  V"},

                            {   "W   W",
                                "W   W",
                                "W W W",
                                "W W W",
                                " WWW"},

                            {   "X   X",
                                " X X",
                                "  X",
                                " X X",
                                "X   X"},

                            {   "Y   Y",
                                " Y Y",
                                "  Y",
                                "  Y",
                                "  Y"},

                            {   "ZZZZZ",
                                "   Z",
                                "  Z",
                                " Z",
                                "ZZZZZ"}
};
